baseURL = "https://artisanml.github.io/"
author = "Ilias Antonopoulos"
copyright = "Copyright © 2025, ARTISAN ML SINGLE MEMBER P.C. - "
relativeURLs = true
languageCode = "en-us"

[pagination]
  pagerSize = 3

title = "ARTISAN ML"
theme = "PaperMod"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[params]
defaultTheme = "auto"
env = "production"
description = "Welcome to ARTISAN ML."
author = "Ilias Antonopoulos"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true

  [params.profileMode]
  enabled = true
  title = "Hi there 👋"
  subtitle = "Welcome to the space of ARTISAN ML."
  imageUrl = "/me.png"
  imageTitle = "me"
  imageWidth = 160
  imageHeight = 160
    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ilias-ant"

    [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ilias-ant"
  
  [params.assets]
  favicon = "/favicons/favicon.ico"
  favicon16x16 = "/favicons/favicon-16x16.png"
  favicon32x32 = "/favicons/favicon-32x32.png"
  apple_touch_icon = "/favicons/apple-touch-icon.png"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]


[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true

  [services.googleAnalytics]
    id = "G-K5FF1NBVCL"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
