baseURL = "https://artisanml.github.io/"
author = "ARTISAN ML"
copyright = "Copyright © 2025, ARTISAN ML P.C. - All rights reserved."
relativeURLs = true
languageCode = "en-us"
title = ""
theme = "PaperMod"

[pagination]
  pagerSize = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
googleAnalytics = "G-PHHSLK594Z"

[params]
defaultTheme = "auto"
env = "production"
description = "Welcome to ARTISAN ML."
author = "ARTISAN ML"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true

  [params.profileMode]
  enabled = true
  title = ""
  subtitle = "Welcome to the space of ARTISAN ML."
  imageUrl = "/artisan-ml-logo.png"
  imageTitle = "artisan-ml-logo"
  imageWidth = 320
  imageHeight = 320

  [params.assets]
  favicon = "/favicons/favicon.ico"
  favicon16x16 = "/favicons/favicon-16x16.png"
  favicon32x32 = "/favicons/favicon-32x32.png"
  apple_touch_icon = "/favicons/apple-touch-icon.png"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[params.Social]
  github = "https://github.com/ilias-ant"
  linkedin = "https://www.linkedin.com/in/ilias-ant"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "products"
    name = "products"
    url = "/products"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
